// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mathfunc.djinni

#import <Foundation/Foundation.h>
@class HWMathFunc;


@interface HWMathFunc : NSObject

+ (nullable HWMathFunc *)create;

- (double)add:(double)a
            b:(double)b;

- (double)subtract:(double)a
                 b:(double)b;

- (double)multiply:(double)a
                 b:(double)b;

- (double)divide:(double)a
               b:(double)b;

@end
