// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from mathfunc.djinni

#pragma once

#include "djinni_support.hpp"
#include "math_func.hpp"

namespace djinni_generated {

class NativeMathFunc final : ::djinni::JniInterface<::mathfunc::MathFunc, NativeMathFunc> {
public:
    using CppType = std::shared_ptr<::mathfunc::MathFunc>;
    using CppOptType = std::shared_ptr<::mathfunc::MathFunc>;
    using JniType = jobject;

    using Boxed = NativeMathFunc;

    ~NativeMathFunc();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeMathFunc>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeMathFunc>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeMathFunc();
    friend ::djinni::JniClass<NativeMathFunc>;
    friend ::djinni::JniInterface<::mathfunc::MathFunc, NativeMathFunc>;

};

}  // namespace djinni_generated
